# Generated by Django 4.1.2 on 2023-06-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0004_useraction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAction',
            new_name='UserActionHistory',
        ),
        migrations.AlterModelOptions(
            name='useractionhistory',
            options={'verbose_name': 'Historia Użytkownika', 'verbose_name_plural': 'Historia Użytkowników'},
        ),
    ]
