# Generated by Django 4.1.2 on 2023-06-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0006_alter_useractionhistory_action_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surename',
            new_name='surname',
        ),
    ]
