# Generated by Django 4.1.2 on 2023-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0007_rename_surename_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionhistory',
            name='action_type',
            field=models.CharField(choices=[('USER_NOTE', 'User note'), ('POINTS_ADDED', 'Points added'), ('POINTS_REMOVED', 'Points removed'), ('USER_LOCATION_CHANGED', 'User location has been changed'), ('USER_PERMISSION_CHANGED', 'User permission has been changed'), ('USER_STATUS_CHANGED', 'User is active/inactive'), ('USER_INSTAGRAM_CHANGED', 'User Instagram name changed'), ('USER_PASSWORD_CHANGED', 'User password has been changed'), ('REWARD_CHANGED', 'Reward changed (ordered/canceled/granted)')], max_length=100),
        ),
    ]
