# Generated by Django 4.1.2 on 2023-06-20 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0008_alter_useractionhistory_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDER_CREATED', 'Order created and awaiting fulfillment'), ('ORDER_APPROVED', 'Order approved, reward retrieved'), ('ORDER_DECLINED', 'Order rejected, user points revoked')], max_length=100)), # noqa E501
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zamawiający')), # noqa E501
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amb_app.reward', verbose_name='Nagroda')), # noqa E501
            ],
        ),
    ]
