# Generated by Django 4.1.2 on 2023-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_code',
            field=models.CharField(default='WRO1', max_length=7, verbose_name='Kod lokacji'),
            preserve_default=False,
        ),
    ]
