# Generated by Django 4.1.2 on 2023-06-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0010_location_location_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienie nagrody', 'verbose_name_plural': 'Zamówienia nagród'},
        ),
    ]
