# Generated by Django 4.1.2 on 2023-06-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0011_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienie Nagrody', 'verbose_name_plural': 'Zamówienia Nagród'},
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Zamówienie zakończone'),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='order_qr_codes', verbose_name='Kod QR'),
        ),
    ]
