# Generated by Django 4.1.2 on 2023-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0012_alter_order_options_order_is_completed_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_qr_code_generated',
            field=models.BooleanField(default=False, verbose_name='Czy QR został utworzony'),
        ),
    ]
