# Generated by Django 4.1.2 on 2023-06-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0013_order_is_qr_code_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ilość'),
        ),
    ]
