import {StyleSheet} from 'react-native'

export default styles = (isDarkMode) => StyleSheet.create({
    wrapper: {
        width: "100%",
        display: 'flex',
        flexDirection: 'column',
        marginTop: 30,
    },
    optionContainer: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        borderRadius: 10,
        backgroundColor: isDarkMode ? "#2e2e2e" : '#F1F1F1',
        marginTop: 10,
        height: 60,
        paddingHorizontal: 15,
        alignItems: 'center',
        justifyContent: 'space-between',
        overflow: 'hidden',
        position: 'relative',
        color: isDarkMode ? '#ffffff' : "#000",
    },
    optionTitle: {
        fontSize: 16,
        fontWeight: 700,
        color: isDarkMode ? "#fff" : "#000",
    },
    optionTxt: {
        color: isDarkMode ? "#fff" : "#000",
    },
    btnContainer: {
        position: 'absolute',
        height: '70%',
        aspectRatio: "1 /1",
        backgroundColor: isDarkMode ? "#121212" : '#FCFCFC',
        borderRadius: 1000,
        justifyContent: 'center',
        alignItems: 'center',
        right: 20,
        overflow: 'hidden',
    },
    msgContainer: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        borderRadius: 10,
        backgroundColor: isDarkMode ? "#2e2e2e" : '#F1F1F1',
        marginVertical: 10,
    },
    infoContainer: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        borderRadius: 10,
        backgroundColor: isDarkMode ? "#2e2e2e" : '#F1F1F1',
        marginTop: 10,
        overflow: 'hidden',
    },
    infoContainerContent: {
        height: 'auto',
        width: '100%',
        paddingHorizontal: 15,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
    },
    infoItem: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    infoItemValue: {
        fontSize: 16, 
        marginLeft: 10,
        color: isDarkMode ? "#fff" : "#000",
    },
    input: {
        flex: 1,
        padding: 6,
    },
    rateAppContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
})