import {StyleSheet} from 'react-native'

export default styles = StyleSheet.create({
    wrapper: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        backgroundColor: '#FCFCFC',
    },
    backBtnContainer: {
        backgroundColor: '#F1F1F1',
        width: '100%',
        height: '10%',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        paddingRight: '5%',

    },
    backBtn: {
        height: '50%',
        aspectRatio: '1/1',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#B4B4B4',
    },
    imgContainer: {
        width: '100%',
        height: '45%',
        backgroundColor: '#F1F1F1',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 6,  
    },
    img: {
        width: '80%',
        aspectRatio: '1 / 2',
    },
    bottomContainer: {
        width: '100%',
        height: '45%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
    },
    descContainer: {
        width: "80%",
        marginHorizontal: '10%',
        paddingVertical: 20,
        height: "30%",
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        
    },
    title: {
        fontWeight: 700,
        fontSize: 24,
    },
    description: {
        fontSize: 16,
        marginTop: 6,
        color: "#8E8E8E",
    },
    amountContainer: {
        width: '60%',
        height: "50%",
        marginHorizontal: '20%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    minusIcon: {
        width: 40,
        height: 40,
        borderRadius: 10,
        display: 'flex',
        flexDirection: "column",
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        borderStyle: 'solid',
        borderWidth: 3,
    },
    plusIcon: {
        width: 40,
        aspectRatio: '1 / 1',
        borderRadius: 10,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
    },
    amount: {
        fontWeight: 700,
        fontSize: 24,
    },
    buyContainer: {
        width: '80%',
        marginHorizontal: '10%',
        height: '20%',
        paddingBottom: 20,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    cost: {
        fontWeight: 700,
        fontSize: 28,
        color: "#34A3CF",
    },
    buyBtn: {
        width: '50%',
        height: "100%",
        borderRadius: 10,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    buyBtnTxt: {
        fontSize: 24,
        textAlign: 'center',
        color: 'white',
    },
})